In [1]:
import grizli
from grizli import grismconf
import numpy as np

In [2]:
conf_file='/Users/lkawinwanichakij/NISPureParallel/CRDS_CACHE/references/jwst/niriss/jwst_niriss_specwcs_0068.asdf'
conf = grismconf.load_grism_config(conf_file)
#crds_conf = grismconf.TransformGrismconf(conf_file=conf_file)

Order -2 = -2 not found in /Users/lkawinwanichakij/crds_cache/references/jwst/niriss/jwst_niriss_photom_0041.fits for GR150C F150W
load_new_sensitivity_curve: only defined for NIRCAM (NIRISS)


In [42]:
grizli_conf_file='/Users/lkawinwanichakij/NISPureParallel/GRIZLI/CONF/GR150C.F150W.221215.conf'
grizli_conf=grismconf.load_grism_config(grizli_conf_file) #grismconf.aXeConf(conf_file=grizli_conf_file)


2025-06-13 14:53:05,813 - stpipe - WARNING - /opt/anaconda3/envs/jadc/lib/python3.12/site-packages/astropy/units/core.py:2145: UnitsWarning: 'FLAM CGS per ELECTRON/S' did not parse as fits unit: At col 0, Unit 'FLAM' not supported by the FITS standard. Did you mean flm? If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html
  warnings.warn(msg, UnitsWarning)

2025-06-13 14:53:05,814 - stpipe - WARNING - /opt/anaconda3/envs/jadc/lib/python3.12/site-packages/astropy/units/core.py:2145: UnitsWarning: 'FLAM CGS per ELECTRON/S' did not parse as fits unit: At col 0, Unit 'FLAM' not supported by the FITS standard. Did you mean flm? If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For detail

# Compare the dxlam of Grizli default conf and CRDS conf
The dxlam for order 'B' from Grizli default conf and CRDS are very different!


In [4]:
conf.dxlam

OrderedDict([('A',
              array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
                      63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
                      76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
                      89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101,
                     102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114,
                     115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
                     128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
                     141, 142])),
             ('C',
              array([336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348,
                     349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361,
                     362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374,
                     375, 376, 377, 378, 379, 380, 381, 382, 383, 38

In [53]:
grizli_conf.dxlam

OrderedDict([('A',
              array([ 49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
                      62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
                      75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
                      88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100,
                     101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
                     114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
                     127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
                     140, 141, 142, 143])),
             ('B',
              array([-220, -219, -218, -217, -216, -215, -214, -213, -212, -211, -210,
                     -209, -208, -207, -206, -205, -204, -203, -202, -201])),
             ('C',
              array([314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326,
                     327, 328, 329, 330, 331, 

This leads to large negative ytrace_beam of order 'B'

In [54]:
beam='B'
x=805.9411557491258
y= 35.39222513887012
ytrace_beam,lam_beam= conf.get_beam_trace(x=x,y=y,dx=conf.dxlam[beam],beam=beam)
print(ytrace_beam)
# dyc = np.asarray(ytrace_beam+20,dtype=int)-20+1 # integer trace
# print(dyc)

# idx = np.arange(9408,dtype=np.int64).reshape((96, 98))
# flat_index =idx[dyc + 47, [47, 48]]
# print(flat_index)

[-1872.45700573 -2033.57017044]


In [57]:
ytrace_beam,lam_beam = grizli_conf.get_beam_trace(x=x,y=y,dx=grizli_conf.dxlam[beam],beam=beam)
print(ytrace_beam)
# dyc = np.asarray(ytrace_beam+20,dtype=int)-20+1 # integer trace
# print(dyc)
# idx = np.arange(9408,dtype=np.int64).reshape((96, 98))

# flat_index =idx[dyc + 47, [47, 48]]
# print(flat_index)

[3.0939076  3.09033012 3.08675588 3.08318489 3.07961713 3.07605261
 3.07249132 3.06893328 3.06537848 3.06182692 3.05827859 3.0547335
 3.05119166 3.04765305 3.04411768 3.04058555 3.03705666 3.03353101
 3.03000859 3.02648942]


In [26]:


# beam = GrismDisperser(id=id,direct=thumb, 
 #                      segmentation=seg_thumb, 
 #                      xcenter=xcenter,
 #                      ycenter=ycenter,
 #                      origin=origin,
 #                      pad=self.pad,
 #                      grow=self.grism.grow,
 #                      beam=b,
 #                      conf=self.conf,
 #                      fwcpos=self.grism.fwcpos,
 #                      MW_EBV=self.grism.MW_EBV)

'-x'

In [30]:
grizli_conf.conf_file

'/Users/lkawinwanichakij/NISPureParallel/GRIZLI/CONF/GR150C.F150W.221215.conf'

In [46]:
def nancy_get_beam_trace(x=None,y=None,dx=None,conf=None,beam=None):
    from astropy.modeling.models import Polynomial2D
    x0 = np.squeeze(conf.transform.reverse(x, y))
    if conf.transform.trace_axis == "+x":
        t_func = conf.conf.INVDISPX
        trace_func = conf.conf.DISPY
        delta = 1 * dx
    elif conf.transform.trace_axis == "-x":
        t_func = conf.conf.INVDISPX
        trace_func = conf.conf.DISPY
        delta = -1 * dx
    elif conf.transform.trace_axis == "+y":
        t_func = conf.conf.INVDISPY
        trace_func = conf.conf.DISPX
        delta = 1 * dx
    else:  # -y
        t_func = conf.conf.INVDISPY
        trace_func = conf.conf.DISPX
        delta = -1 * dx
    t = t_func(conf.order_names[beam], *x0, delta)
    tdx = conf.conf.DISPX(conf.order_names[beam], *x0, t)
    tdy = conf.conf.DISPY(conf.order_names[beam], *x0, t)

    rev = conf.transform.forward(x0[0] + tdx, x0[1] + tdy)
    trace_dy = rev[1, :] - y
    return trace_dy

In [47]:
trace_dy = nancy_get_beam_trace(x=x,y=y,dx=conf.dxlam[beam],beam=beam,conf=conf)

In [48]:
trace_dy

array([-1872.45700573, -2033.57017044])